### ISSUE TITLE
output "Basic state of m_nounlock seems to be 'false', but table::unlockRow() seems to call unlock_row() only when 'false'." often

### ISSUE THREAD

**Issue by kinoyasu** [bizstation/transactd#15]
(built 5.6.23 + 2.2.0; using transaction;)

Basic state of m_nounlock seems to be 'false', and 'true' when cursor row is locked.
But table::unlockRow() seems to call unlock_row() only when m_nounlock==false.
So, InnoDB outputs the Error log even just for nstable::seek().

2015-02-13 12:08:04 7ffff7e22700 InnoDB: Error: unlock row could not find a 3 mode lock on the record
2015-02-13 12:08:04 7ffff7e22700 InnoDB: current statement:

Is the suggested fix valid?
<pre>
--- transactd_orig_2.2.0/source/bzs/db/engine/mysql/database.cpp        2015-01-18 00:05:52.000000000 +0900
+++ mysql-5.6.23_td_test/plugin/transactd/source/bzs/db/engine/mysql/database.cpp       2015-02-13 12:42:08.170204003 +0900
@@ -1418,7 +1418,7 @@ inline void table::tryConsistentRead(boo

 inline void table::unlockRow(bool noConsistent)
 {
-    if ((m_forceConsistentRead || m_db.canUnlockRow()) && m_validCursor && !m_nounlock)
+    if ((m_forceConsistentRead || m_db.canUnlockRow()) && m_validCursor && m_nounlock)
         m_table->file->unlock_row();
     tryConsistentRead(noConsistent);
     m_nounlock = false;

</pre>

**Comment by bizstation** [comment]
Thank you for your comments.

m_nounlock will be set to true when table::del, table::update or table::insert succeeded.
If the last operation is the one of them, handler::unlock_row is not called to keep lock.

Thank you for your patch, but, testMultiDatabase in test_tdclcpp will be failed with it.

To examine more in detail, could you give me the snippets which reproduces InnoDB error?
Any help would be appreciated.

**Comment by kinoyasu** [comment]
The problematic sequence is...
(In 1 transaction)
table->seek();
...
table->unlock();
....
table->seek();

The second seek() causes table::unlockRow() at server before the seek, even the previous unlock() already has caused table::unlock() for the record at the server.
