### ISSUE TITLE
can't install transactd c++ client on windows 7

### ISSUE THREAD

**Issue by silverist** [bizstation/transactd#19]
i tried to install transactd c++ client on windows 7 x64.
but output as follows, can't install

>C:\Program Files\transactd-client-win64_with_sdk-2.4.4>install.cmd
>Too many command line params!
>C:\Program Files\transactd-client-win64_with_sdk-2.4.4\setpath.vbs(22, 2) Microsoft VBScript 実行時エラー: 書き込みでき ません。
>
>.
>.
>"C:\Program Files\transactd-client-win64_with_sdk-2.4.4\" was added to the environment variable Path.
>.
>.
>Can not register bin\tdclatl.dll. You can not use COM(Active X) client.
>.
>... Done. Please push any key :

**Comment by bizstation** [comment]
I was able to reproduce the problem.
It is the problem of `install.cmd`.
Please use this fixed version of `install.cmd`:
```batch
@echo off
set dir=%~d0%~p0
cscript "%dir%setpath.vbs" //nologo "%dir%bin"

echo;

if ERRORLEVEL==1 (
  echo "%dir%bin" has already registered the environment variable Path.
) else (
  echo "%dir%bin" was added to the environment variable Path.
)

echo;

set cpu=32
if EXIST bin\tdclc_64_*.dll set cpu=64
if not EXIST %windir%\syswow64\regsvr32.exe set cpu=64

if "%cpu%"=="64" %windir%\system32\regsvr32.exe "%dir%bin\tdclatl.dll" /s
if "%cpu%"=="32" %windir%\syswow64\regsvr32.exe "%dir%bin\tdclatl.dll" /s

if ERRORLEVEL==1 (
  echo Can not register "%dir%bin\tdclatl.dll". You can not use COM^(Active X^) client.
) else (
  echo "%dir%bin\tdclatl.dll" has been registered.
)

echo;

echo ... Done.
pause
```

We are going to fix ZIP packages soon.
Thank you to your reporting.

**Comment by bizstation** [comment]
Note: In addition, please run `install.cmd` as the **Administrator**.

**Comment by silverist** [comment]
Thank you to your response.

I did not run install.cmd as the Administrator.
I run it as the Administrator, it works.
