### ISSUE TITLE
can't run TestClient.cmd on windows 7 x64

### ISSUE THREAD

**Issue by silverist** [bizstation/transactd#20]
i ran install.cmd as the Administrator.
In the next step, i tried to run TestClient.cmd as the Administrator after 9th line as follows
>before: if EXIST tdclc_64_2_0.dll set cpu=64
>after   : if EXIST tdclc_64_2_4.dll set cpu=64

but, output as follows and commented out 66-68th lines, then it works.
Should i run bench_tdclcpp_vc100_64m.exe? it does not exist in the 'vc100' folder.

>Starting bench mark of read write operation Multibyte dll ...
>'vc100\bench_tdclcpp_vc100_64m.exe' は、内部コマンドまたは外部コマンド、操作可能なプログラムまたはバッチ ファイルとして認識されていません。
>...Error occured. Please push any key :

**Comment by bizstation** [comment]
We were able to reproduce the problem.
It is the problem of  test scripts, and fixed now.

Please re-download latest ZIP package.
http://www.bizstation.jp/al/transactd/download/index.html
(Binary files are not changed, only scripts are updated.)

**Comment by silverist** [comment]
Thank you to your response.
All as follows work.
>・install.cmd
>・TestClient.cmd
>・TestClient_ATL.cmd
