### ISSUE TITLE
I want to do bulkinsert in C++ on Win7 by transactd client 2.4

### ISSUE THREAD

**Issue by silverist** [bizstation/transactd#21]
I'm able to insert by following the tutorial 
>http://www.bizstation.jp/ja/transactd/documents/tutorial.html?lang=cpp
and the sample
>http://www.bizstation.jp/ja/transactd/client/sdk/doc/exs_insert_record.html

But, I guess that I'm not able to do bulkinsert, need to use autoBulkinsert class.
How do I use it?
Or May I have another means?

**Comment by bizstation** [comment]
"bulk insert" collects insert operations to internal cache and sends them all together to server.
Call `beginBulkInsert` before insert operations, and call `commitBulkInsert` after them.
```c++
table* tb = db->opneTbale("user");
tb->beginBulkInsert(BULKBUFSIZE);
for (int I = 0; I < 10; ++i)
{
    tb->clearBuffer();
    tb->setFV(“id”, I + 1);
    tb->insert();
}
tb->commitBulkInsert();
tb->close();
```

`autoBulkinsert` class calls `commitBulkInsert` automatically in destructor. Use it as an automatic variable.
```c++
table_ptr*  tb = openTbale(db, "user");
{
    autoBulkinsert at(tb); // Call beginBulkInsert
    for (I = 0; I < 10 ; ++i)
    {
        tb->clearBuffer();
        tb->setFV("id", I + 1);
        tb->insert();
    } // Call commitBulkInsert automatically.
}
tb->close();
```

**Comment by silverist** [comment]
Thanks to your response.
I'm able to do bulkinsert.
