### ISSUE TITLE
cause link error when  link with transactd client 2.4 and boost library

### ISSUE THREAD

**Issue by silverist** [bizstation/transactd#22]
I put build command as follows on Win7 MinGW g++(gcc)
>g++ -Wall -o PL_auto_db_insert PL_auto_db_insert.o json11.o time_utility.o  -sta
tic -lboost_date_time-mgw49-mt-1_55 -lboost_filesystem-mgw49-mt-1_55 -lboost_sys
tem-mgw49-mt-1_55 -ltdclcpp_vc100_64m_2_4

output as follows.(however, there is no compile error)
Is the reason build on MinGW g++(gcc) ?
>PL_auto_db_insert.o:PL_auto_db_insert.cpp:(.text+0xd14): undefined reference to
`bzs::db::protocol::tdap::client::database::create()'
PL_auto_db_insert.o:PL_auto_db_insert.cpp:(.text+0xd4f): undefined reference to
`bzs::db::protocol::tdap::client::database::open(char const*, short, short, char
 const*, char const*)'
PL_auto_db_insert.o:PL_auto_db_insert.cpp:(.text+0xd83): undefined reference to
`bzs::db::protocol::tdap::client::database::openTable(char const*, short, bool,
char const*, char const*)'
PL_auto_db_insert.o:PL_auto_db_insert.cpp:(.text+0xd9e): undefined reference to
`bzs::db::protocol::tdap::client::nstable::beginBulkInsert(int)'
PL_auto_db_insert.o:PL_auto_db_insert.cpp:(.text+0xe0d): undefined reference to
`bzs::db::protocol::tdap::client::table::clearBuffer()'
PL_auto_db_insert.o:PL_auto_db_insert.cpp:(.text+0xe86): undefined reference to
`bzs::db::protocol::tdap::client::table::setFV(char const*, int)'
PL_auto_db_insert.o:PL_auto_db_insert.cpp:(.text+0xea5): undefined reference to
`bzs::db::protocol::tdap::client::table::setFV(char const*, int)'
PL_auto_db_insert.o:PL_auto_db_insert.cpp:(.text+0xec7): undefined reference to
`bzs::db::protocol::tdap::client::table::setFV(char const*, double)'
PL_auto_db_insert.o:PL_auto_db_insert.cpp:(.text+0xf78): undefined reference to
`bzs::db::protocol::tdap::client::database::destroy(bzs::db::protocol::tdap::cli
ent::database*)'
PL_auto_db_insert.o:PL_auto_db_insert.cpp:(.text$_ZN3bzs2db8protocol4tdap6client
7nstable6insertEb[_ZN3bzs2db8protocol4tdap6client7nstable6insertEb]+0x1c): undef
ined reference to `bzs::db::protocol::tdap::client::nstable::doInsert(bool)'
PL_auto_db_insert.o:PL_auto_db_insert.cpp:(.text$_ZN3bzs2db8protocol4tdap6client
5table5setFVEPKcS6_[_ZN3bzs2db8protocol4tdap6client5table5setFVEPKcS6_]+0x27): u
ndefined reference to `bzs::db::protocol::tdap::client::table::setFVA(char const
*, char const*)'
collect2.exe: error: ld returned 1 exit status
objfiles:4: recipe for target 'a.out' failed
mingw32-make: *** [a.out] Error 1

**Comment by bizstation** [comment]
It seems to me that you want to build your C++ program with **MinGW**, but you tried to link against `tdclcpp_vc100_64m_2_4.dll` that compiled with **Visual Studio**.
You have to link against `tdclcpp*.dll` that compiled with MinGW.

We do not provide pre-built binaries which compiled with MinGW. But it can be built from source code with some patches. We'll explain that how to build `tdclcpp_mgwXX_64m_2_4.dll`.

(Please note that we did not test these binaries well now.)

1. Download transactd source code archive and extract it.
2. Install CMake. (to generate makefile.)
3. Rename some `CMakeLists.txt` to `CMakeLists.txt_` with following commands:
   
   ```
   cd path\to\transactd-source-2.4.4
   rename build\bench_query\CMakeLists.txt CMakeLists.txt_
   rename build\bench_td\CMakeLists.txt CMakeLists.txt_
   rename build\ormsrcgen\CMakeLists.txt CMakeLists.txt_
   rename build\querystmts\CMakeLists.txt CMakeLists.txt_
   rename build\tdclc\CMakeLists.txt CMakeLists.txt_
   rename build\tdclstmt\CMakeLists.txt CMakeLists.txt_
   rename build\test_tdcl\CMakeLists.txt CMakeLists.txt_
   ```
   
   (Disable building these projects temporarily.)
4. Patch `build/tdclcpp/CMakeLists.txt`:
   
   ```diff
    @@ -139,7 +139,7 @@ else()
         LINUX)
     else()
       set_property(TARGET ${this_target} APPEND PROPERTY COMPILE_DEFINITIONS
    -     WIN32 _WIN32)
    +     WIN32 _WIN32 _SYS_TIME_H_ _GETTIMEOFDAY_DEFINED)
     endif()
   endif()
   if(TRANSACTD_RUBY_GEM OR TRANSACTD_PHP)
   ```
5. Run CMake command:
   
   ```
   mkdir bld_mgw
   cd bld_mgw
   cmake .. -G "MSYS Makefiles" ^
     -DBOOST_ROOT="C:\path\to\boost_MinGWx64" ^
     -DWITH_TRANSACTD_SERVER=OFF -DWITH_TRANSACTD_CLIENTS=ON
   ```
6. Run make command:
   
   ```
   make
   ```

Then `bld_mgw/bin/tdclcpp_mgwXX_64m_2_4.dll` will be created. Try to use it instead of `tdclcpp_vc100_64m_2_4.dll`.

**Comment by silverist** [comment]
Thank you to your response.

But, 5th step not work and output as follows becaue -DBOOST_ROOT option not set.
Do the option mean the path .lib files?(install boost 1.58 "C:/msys/1.0/boost/boost_1_58_0")
Or another?

>ERRORInvalid project name tdclcpp
-- tdclcpp FileVersion 2.4.4.97
-- Could NOT find Boost
CMake Error at build/common/transactd_common.cmake:285 (message):
  Boost not found.  C:/msys/1.0/boost/boost_1_58_0
Call Stack (most recent call first):
  build/tdclcpp/CMakeLists.txt:161 (transactd_link_boost_libraries)

**Comment by silverist** [comment]
Thank you to your response.

* MinGW(mingw-w64) installed: C:\mingw-w64
* Boost 1.58 installed: C:\boost\boost_1_58_0
* transactd 2.4.4 source placed: C:\transactd-source-2.4.4

But, 5th step not work on the above setting.
The following are command and output.
after all, can I build it on MinGW?

■command
```
cmake .. -G "MSYS Makefiles" 
 -DCMAKE_MAKE_PROGRAM="C:/mingw-w64/x86_64-5.2.0-posix-seh-rt_v4-rev0/mingw64/bin/mingw32-make.exe" 
 -DCMAKE_AR="C:/mingw-w64/x86_64-5.2.0-posix-seh-rt_v4-rev0/mingw64/bin/ar.exe" 
 -DCMAKE_CXX_COMPILER="C:/mingw-w64/x86_64-5.2.0-posix-seh-rt_v4-rev0/mingw64/bin/g++.exe" 
 -DBOOST_ROOT="C:/boost/boost_1_58_0"  
 -DWITH_TRANSACTD_SERVER=OFF
 -DWITH_TRANSACTD_CLIENTS=ON
```
■output
```
-- BUILD Transactd Client Libraries
-- The C compiler identification is GNU 5.2.0
-- The CXX compiler identification is GNU 5.2.0
-- Check for working C compiler: C:/mingw-w64/x86_64-5.2.0-posix-seh-rt_v4-rev0/mingw64/bin/gcc.exe
-- Check for working C compiler: C:/mingw-w64/x86_64-5.2.0-posix-seh-rt_v4-rev0/mingw64/bin/gcc.exe -- broken
CMake Error at C:/CMake/share/cmake-3.4/Modules/CMakeTestCCompiler.cmake:61 (message):
  The C compiler
  "C:/mingw-w64/x86_64-5.2.0-posix-seh-rt_v4-rev0/mingw64/bin/gcc.exe" is not
  able to compile a simple test program.

  It fails with the following output:

   Change Dir: C:/transactd-source-2.4.4/bld_mgw/CMakeFiles/CMakeTmp



  Run Build
  Command:"C:/mingw-w64/x86_64-5.2.0-posix-seh-rt_v4-rev0/mingw64/bin/mingw32-make.exe"
  "cmTC_ba191/fast"


  C:/mingw-w64/x86_64-5.2.0-posix-seh-rt_v4-rev0/mingw64/bin/mingw32-make.exe
  -f CMakeFiles/cmTC_ba191.dir/build.make CMakeFiles/cmTC_ba191.dir/build

  mingw32-make.exe[1]: Entering directory
  'C:/transactd-source-2.4.4/bld_mgw/CMakeFiles/CMakeTmp'

  CMakeFiles/cmTC_ba191.dir/build.make:65: recipe for target
  'CMakeFiles/cmTC_ba191.dir/testCCompiler.c.obj' failed

  process_begin: CreateProcess(NULL, sh.exe -c "/C/CMake/bin/cmake.exe -E
  cmake_echo_color --switch=
  --progress-dir=/C/transactd-source-2.4.4/bld_mgw/CMakeFiles/CMakeTmp/CMakeFiles
  --progress-num=1 Building C object
  CMakeFiles/cmTC_ba191.dir/testCCompiler.c.obj", ...) failed.

  make (e=2): 指定されたファイルが見つかりません。

  mingw32-make.exe[1]: *** [CMakeFiles/cmTC_ba191.dir/testCCompiler.c.obj]
  Error 2

  mingw32-make.exe[1]: Leaving directory
  'C:/transactd-source-2.4.4/bld_mgw/CMakeFiles/CMakeTmp'

  makefile:126: recipe for target 'cmTC_ba191/fast' failed

  mingw32-make.exe: *** [cmTC_ba191/fast] Error 2





  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:99 (project)


-- Configuring incomplete, errors occurred!
See also "C:/transactd-source-2.4.4/bld_mgw/CMakeFiles/CMakeOutput.log".
See also "C:/transactd-source-2.4.4/bld_mgw/CMakeFiles/CMakeError.log".
```

**Comment by bizstation** [comment]
The error message says:
> process_begin: CreateProcess(NULL, sh.exe -c "/C/CMake/bin/cmake.exe -E
>   cmake_echo_color --switch=
>   --progress-dir=/C/transactd-source-2.4.4/bld_mgw/CMakeFiles/CMakeTmp/CMakeFiles
>   --progress-num=1 Building C object
>   CMakeFiles/cmTC_ba191.dir/testCCompiler.c.obj", ...) failed.
> 
>   make (e=2): 指定されたファイルが見つかりません。

This probably means that CMake could not find `sh.exe`.

I succeeded to build `tdclcpp_mgw52_64m_2_4.dll` with the following environments:
* Windows 7 64 bit
* [MinGW-w64 - for 32 and 64 bit Windows](http://sourceforge.net/projects/mingw-w64/) version 5.2
* [MSYS-1.0.11](http://sourceforge.net/projects/mingw/files/MSYS/Base/msys-core/msys-1.0.11/MSYS-1.0.11.exe/download)

I referenced this page to setup my MinGW environments.
[PENGUINITIS - MinGW 64 bit 版 のセットアップ](http://www.geocities.co.jp/penguinitis2002/computer/programming/MinGW-w64.html)

1. Install [MinGW-w64 - for 32 and 64 bit Windows](http://sourceforge.net/projects/mingw-w64/).
   The installation path is `C:\mingw-w64\x86_64-5.2.0-posix-seh-rt_v4-rev0`.

2. Build Boost for MinGW-w64.
   
   ```
   "C:\mingw-w64\x86_64-5.2.0-posix-seh-rt_v4-rev0\mingw-w64.bat"
   cd C:\path\to\boost_1_58_0_x64
   bootstrap.bat gcc
   b2.exe -sTOOLS=mingw toolset=gcc threading=multi address-model=64 architecture=x86 ^
     --with-chrono --with-filesystem --with-system --with-thread --with-timer ^
     --with-serialization --with-program_options ^
     variant=debug,release link=static runtime-link=static,shared
   ```
   
   Then files like `stage\lib\libboost_system-mgw52-mt-1_58.a` or `stage\lib\libboost_system-mgw52-mt-s-1_58.a` are built.

3. I tried to run CMake command, but got same error with you.

4. Install [MSYS-1.0.11](http://sourceforge.net/projects/mingw/files/MSYS/Base/msys-core/msys-1.0.11/MSYS-1.0.11.exe/download).
   The installation path is `C:\msys`.

5. Rename `C:\msys\1.0\bin\make.exe` to `C:\msys\1.0\bin\mingw32-make.exe` according to installation notice message.

6. Double click `C:\msys\1.0\msys.bat` to open MINGW prompt.

7. Set MinGW-w64 path to environment `PATH` value.
   
   ```
   PATH=/c/mingw-w64/x86_64-5.2.0-posix-seh-rt_v4-rev0/mingw64/bin:${PATH}
   ```

8. Run CMake command.
   
   ```
   cd /c/path/to/transactd-source-2.4.4/bldmgw
   cmake .. -G "MSYS Makefiles" \
    -DBOOST_ROOT="C:\path\to\boost_1_58_0_x64" \
    -DWITH_TRANSACTD_SERVER=OFF -DWITH_TRANSACTD_CLIENTS=ON \
    -DCMAKE_MAKE_PROGRAM="C:\mingw-w64\x86_64-5.2.0-posix-seh-rt_v4-rev0\mingw64\bin\mingw32-make.exe"
   ```

9. Run `make` command.
   
   ```
   /C/mingw-w64/x86_64-5.2.0-posix-seh-rt_v4-rev0/mingw64/bin/mingw32-make.exe
   ```

10. Build success and the following files were built:
   
   * c:\path\to\transactd-source-2.4.4\bldmgw\bin\tdclcpp_mgw52_64m_2_4.dll
   * c:\path\to\transactd-source-2.4.4\bldmgw\lib\libtdclcpp_mgw52_64m_2_4.dll.a

**Comment by silverist** [comment]
Thank you to your response.
I tried them, and success "Run CMake command." step, but failed "Run make command" step.

But as #23, i can built tdclcpp on VS2015.
Then I'm probably able to use tdclcpp on my program, so I close this issue once.

**Comment by bizstation** [comment]
I'm glad to hear that. :smile: 
If possible, would you tell me your make error message?
We want to know problems in our source code.

**Comment by silverist** [comment]
I'm sorry for the late reply.
The following is the error message I make at "Run make command" step.
I hope it is useful for you.

```
[  1%] Building CXX object build/tdclc/CMakeFiles/tdclc.dir/__/__/source/bzs/db/protocol/tdap/client/client.cpp.obj
c:/transactd-source-2.4.4/source/bzs/db/protocol/tdap/client/client.cpp:1:0: warning: -fPIC ignored for target (all code is position independent)
 /* =================================================================
 ^
In file included from C:/transactd-source-2.4.4/source/bzs/db/protocol/tdap/tdapSchema.h:27:0,
                 from c:/transactd-source-2.4.4/source/bzs/db/protocol/tdap/client/sqlBuilder.h:21,
                 from c:/transactd-source-2.4.4/source/bzs/db/protocol/tdap/client/client.h:21,
                 from c:/transactd-source-2.4.4/source/bzs/db/protocol/tdap/client/client.cpp:19:
C:/transactd-source-2.4.4/source/bzs/env/crosscompile.h:132:0: warning: "_ltot_s" redefined
 #define _ltot_s(A, B, C, D) _ltot(A, B, D)
 ^
In file included from c:/mingw-w64/x86_64-5.2.0-posix-seh-rt_v4-rev0/mingw64/x86_64-w64-mingw32/include/tchar.h:1132:0,
                 from C:/transactd-source-2.4.4/source/bzs/db/protocol/tdap/tdapcapi.h:22,
                 from C:/transactd-source-2.4.4/source/bzs/db/protocol/tdap/tdapSchema.h:22,
                 from c:/transactd-source-2.4.4/source/bzs/db/protocol/tdap/client/sqlBuilder.h:21,
                 from c:/transactd-source-2.4.4/source/bzs/db/protocol/tdap/client/client.h:21,
                 from c:/transactd-source-2.4.4/source/bzs/db/protocol/tdap/client/client.cpp:19:
c:/mingw-w64/x86_64-5.2.0-posix-seh-rt_v4-rev0/mingw64/x86_64-w64-mingw32/include/sec_api/tchar_s.h:146:0: note: this is the location of the previous definition
 #define _ltot_s _ltoa_s
 ^
In file included from C:/transactd-source-2.4.4/source/bzs/db/protocol/tdap/tdapSchema.h:27:0,
                 from c:/transactd-source-2.4.4/source/bzs/db/protocol/tdap/client/sqlBuilder.h:21,
                 from c:/transactd-source-2.4.4/source/bzs/db/protocol/tdap/client/client.h:21,
                 from c:/transactd-source-2.4.4/source/bzs/db/protocol/tdap/client/client.cpp:19:
C:/transactd-source-2.4.4/source/bzs/env/crosscompile.h:133:0: warning: "_ultot_s" redefined
 #define _ultot_s(A, B, C, D) _ultot(A, B, D)
 ^
In file included from c:/mingw-w64/x86_64-5.2.0-posix-seh-rt_v4-rev0/mingw64/x86_64-w64-mingw32/include/tchar.h:1132:0,
                 from C:/transactd-source-2.4.4/source/bzs/db/protocol/tdap/tdapcapi.h:22,
                 from C:/transactd-source-2.4.4/source/bzs/db/protocol/tdap/tdapSchema.h:22,
                 from c:/transactd-source-2.4.4/source/bzs/db/protocol/tdap/client/sqlBuilder.h:21,
                 from c:/transactd-source-2.4.4/source/bzs/db/protocol/tdap/client/client.h:21,
                 from c:/transactd-source-2.4.4/source/bzs/db/protocol/tdap/client/client.cpp:19:
c:/mingw-w64/x86_64-5.2.0-posix-seh-rt_v4-rev0/mingw64/x86_64-w64-mingw32/include/sec_api/tchar_s.h:147:0: note: this is the location of the previous definition
 #define _ultot_s _ultoa_s
 ^
In file included from C:/transactd-source-2.4.4/source/bzs/db/protocol/tdap/tdapSchema.h:27:0,
                 from c:/transactd-source-2.4.4/source/bzs/db/protocol/tdap/client/sqlBuilder.h:21,
                 from c:/transactd-source-2.4.4/source/bzs/db/protocol/tdap/client/client.h:21,
                 from c:/transactd-source-2.4.4/source/bzs/db/protocol/tdap/client/client.cpp:19:
C:/transactd-source-2.4.4/source/bzs/env/crosscompile.h:134:0: warning: "_i64tot_s" redefined
 #define _i64tot_s(A, B, C, D) _i64tot(A, B, D)
 ^
In file included from c:/mingw-w64/x86_64-5.2.0-posix-seh-rt_v4-rev0/mingw64/x86_64-w64-mingw32/include/tchar.h:1132:0,
                 from C:/transactd-source-2.4.4/source/bzs/db/protocol/tdap/tdapcapi.h:22,
                 from C:/transactd-source-2.4.4/source/bzs/db/protocol/tdap/tdapSchema.h:22,
                 from c:/transactd-source-2.4.4/source/bzs/db/protocol/tdap/client/sqlBuilder.h:21,
                 from c:/transactd-source-2.4.4/source/bzs/db/protocol/tdap/client/client.h:21,
                 from c:/transactd-source-2.4.4/source/bzs/db/protocol/tdap/client/client.cpp:19:
c:/mingw-w64/x86_64-5.2.0-posix-seh-rt_v4-rev0/mingw64/x86_64-w64-mingw32/include/sec_api/tchar_s.h:148:0: note: this is the location of the previous definition
 #define _i64tot_s _i64toa_s
 ^
In file included from C:/boost/boost_1_58_0/boost/date_time/posix_time/posix_time_types.hpp:11:0,
                 from C:/boost/boost_1_58_0/boost/asio/time_traits.hpp:23,
                 from C:/boost/boost_1_58_0/boost/asio/deadline_timer_service.hpp:27,
                 from C:/boost/boost_1_58_0/boost/asio/basic_deadline_timer.hpp:25,
                 from C:/boost/boost_1_58_0/boost/asio.hpp:22,
                 from C:/transactd-source-2.4.4/source/bzs/netsvc/client/iconnection.h:27,
                 from c:/transactd-source-2.4.4/source/bzs/db/protocol/tdap/client/request.h:23,
                 from c:/transactd-source-2.4.4/source/bzs/db/protocol/tdap/client/client.h:22,
                 from c:/transactd-source-2.4.4/source/bzs/db/protocol/tdap/client/client.cpp:19:
C:/boost/boost_1_58_0/boost/date_time/microsec_time_clock.hpp: In static member function 'static time_type boost::date_time::microsec_clock<time_type>::create_time(boost::date_time::microsec_clock<time_type>::time_converter)':
C:/boost/boost_1_58_0/boost/date_time/microsec_time_clock.hpp:84:26: error: call of overloaded 'gettimeofday(timeval*&, int)' is ambiguous
       gettimeofday(&tv, 0); //gettimeofday does not support TZ adjust on Linux.
                          ^
In file included from C:/transactd-source-2.4.4/source/bzs/db/protocol/tdap/tdapSchema.h:27:0,
                 from c:/transactd-source-2.4.4/source/bzs/db/protocol/tdap/client/sqlBuilder.h:21,
                 from c:/transactd-source-2.4.4/source/bzs/db/protocol/tdap/client/client.h:21,
                 from c:/transactd-source-2.4.4/source/bzs/db/protocol/tdap/client/client.cpp:19:
C:/transactd-source-2.4.4/source/bzs/env/crosscompile.h:43:5: note: candidate: int gettimeofday(timeval*, timezone*)
 int gettimeofday(struct timeval*, struct timezone*);
     ^
In file included from C:/boost/boost_1_58_0/boost/date_time/c_time.hpp:31:0,
                 from C:/boost/boost_1_58_0/boost/date_time/time_clock.hpp:16,
                 from C:/boost/boost_1_58_0/boost/date_time/posix_time/posix_time_types.hpp:10,
                 from C:/boost/boost_1_58_0/boost/asio/time_traits.hpp:23,
                 from C:/boost/boost_1_58_0/boost/asio/deadline_timer_service.hpp:27,
                 from C:/boost/boost_1_58_0/boost/asio/basic_deadline_timer.hpp:25,
                 from C:/boost/boost_1_58_0/boost/asio.hpp:22,
                 from C:/transactd-source-2.4.4/source/bzs/netsvc/client/iconnection.h:27,
                 from c:/transactd-source-2.4.4/source/bzs/db/protocol/tdap/client/request.h:23,
                 from c:/transactd-source-2.4.4/source/bzs/db/protocol/tdap/client/client.h:22,
                 from c:/transactd-source-2.4.4/source/bzs/db/protocol/tdap/client/client.cpp:19:
c:/mingw-w64/x86_64-5.2.0-posix-seh-rt_v4-rev0/mingw64/x86_64-w64-mingw32/include/sys/time.h:42:13: note: candidate: int gettimeofday(timeval*, void*)
 int __cdecl gettimeofday(struct timeval *__restrict__,
             ^
build/tdclc/CMakeFiles/tdclc.dir/build.make:88: recipe for target 'build/tdclc/CMakeFiles/tdclc.dir/__/__/source/bzs/db/protocol/tdap/client/client.cpp.obj' failed
mingw32-make[2]: *** [build/tdclc/CMakeFiles/tdclc.dir/__/__/source/bzs/db/protocol/tdap/client/client.cpp.obj] Error 1
CMakeFiles/Makefile2:85: recipe for target 'build/tdclc/CMakeFiles/tdclc.dir/all' failed
mingw32-make[1]: *** [build/tdclc/CMakeFiles/tdclc.dir/all] Error 2
makefile:83: recipe for target 'all' failed
mingw32-make: *** [all] Error 2
```

**Comment by bizstation** [comment]
Thank you for your reporting! :+1: 

In the error message, it seems to me that you tried to build `tdclc`. (In the other word, you failed to disable `tdclc`.)
`tdclc` is not able to build by MinGW, now. Use `tdclc.dll` which is provided as prebuilt binary or is built by VisualStudio. They work with `tdclcpp_mgw*.dll` which is built by MinGW.

Check these points (if you want to try to solve the problem):
* build/tdclc/CMakeLists.txt *MUST NOT* exist to disable `tdclc`. Check step 3 on [this comment](https://github.com/bizstation/transactd/issues/22#issuecomment-146426123).
* Perhaps, you have to clean up your build directory once, because old build information remains. Clean up bld_mgw directory and retry from CMake command.

**Comment by silverist** [comment]
Thank you to your response.
Not to do "step3"(https://github.com/bizstation/transactd/issues/22#issuecomment-146426123) makes those errors.
After the step do, try again, and I'm sure to build.
