### ISSUE TITLE
can't open database by connecting tdclcpp

### ISSUE THREAD

**Issue by silverist** [bizstation/transactd#25]
I make execution error at "db->open" line in the following C++11 code.
As a premise, I can build this program with no error.
Then I think that I set #include files, namespaces, and so on properly to use tdclcpp.

```C++
	static const _TCHAR* uri = _T("tdap://root@localhost/ilte_line?dbfile=transactd_schema&pwd=r4nk0r4nk0");
	database* db = database::create();
	db->open(uri, TYPE_SCHEMA_BDF, TD_OPEN_NORMAL);
```

**Comment by bizstation** [comment]
What is the error number, that db->stat() returns.
And please look at the cause from the error code table.
http://www.bizstation.jp/ja/transactd/client/sdk/doc/page_6error_code.html

Probably,You  have not installed the tdclc_64_2_4.dll to system32 directory or directory of the PATH environment variable ?

Thanks.

**Comment by silverist** [comment]
Thank you to your response.

>What is the error number, that db->stat() returns.

As the following code, db->stat() return 0 at the "before open database" line.
And db->stat() can't return because the program hung up at the "after open database" line.

```C++
	static const _TCHAR* uri = _T("tdap://root@localhost/ilte_line?dbfile=transactd_schema&pwd=r4nk0r4nk0");
	database* db = database::create();
ofs << "db stat before open:" << db->stat() << std::endl;
	db->open(uri, TYPE_SCHEMA_BDF, TD_OPEN_NORMAL);
ofs << "db stat after open:" << db->stat() << std::endl;
```

>Probably,You have not installed the tdclc_64_2_4.dll to system32 directory or directory of the PATH environment variable ?

No, I installed tdclc_64_2_4.dll at the same directory as tdclcpp_vc140_64ur_2_4.dll and added it to PATH environment variable.

**Comment by bizstation** [comment]
Which has occurred, "execution error" or "hung up"?
Were there any error messages? Can you paste it here?
The information is not enough to solve or reproduce the problem.

If we try to solve this problem with current information, one of the way is that:
1. Build `tdclcpp*.dll` with debug option.
2. Run program, and step in the code with Visual Studio.

**Comment by silverist** [comment]
Thank you to your response.

I'm sorry that I fix [PreProcessor definition] in [Configuration Properties] - [C/C++] - [PreProcessor] properly and rebuild,then my program run with no execution error.

Probably, when I change [Active solution configuration], [PreProcessor definition] change incorrectly and happen the execution error(and hung up).
