### ISSUE TITLE
Plugin Comparison

### ISSUE THREAD

**Issue by orz--** [bizstation/transactd#38]
I saw the following URL.

Transactd Advantage over other NoSQL plugins
http://www.bizstation.jp/en/transactd/plugin_compare.html

I think handlersocket isn't supporting it with MySQL 5.7.

for example:
https://www.percona.com/doc/percona-server/LATEST/changed_in_57.html
https://www.slideshare.net/yoku0825/mysql-57mysql-80
P.25

Please check it.

**Comment by bizstation** [comment]
We fixed the page.
Thank you for your advice.
