### ISSUE TITLE
I have a question

### ISSUE THREAD

**Issue by orz--** [bizstation/transactd#39]
Is this support MySQL 8.0 and MariaDB 10.2 ?
I hope for addition of this information in following comparative chart.
Thank you.
http://www.bizstation.jp/en/transactd/plugin_compare.html

**Comment by bizstation** [comment]
Thank you for your inquiry.
MariaDb 10.2 is supported.
MySQL 8.0 will be supported.

We'd like to update the chart.
Thank you.

**Comment by bizstation** [comment]
We updated the chart.
http://www.bizstation.jp/en/transactd/plugin_compare.html

**Comment by orz--** [comment]
Thank you for updated.
